import styles from "@/styles/Home.module.css";
import { IShortcut, ShortcutHandler } from "@/utils/shortcut";
import { Inter } from "next/font/google";
import Head from "next/head";
import { useEffect, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [shortcut, setShortcut] = useState<string>();

  const [shortcuts] = useState<IShortcut[]>([
    {
      code: "KeyS",
      callback: () => {
        console.log("Serviço");
        setShortcut("Serviço -> KeyS");
      },
    },
    {
      code: "KeyM",
      callback: () => {
        console.log("Motorista");
        setShortcut("Motorista -> KeyM");
      },
    },
    {
      code: "KeyE",
      callback: () => {
        console.log("Entrega");
        setShortcut("Entrega -> KeyE");
      },
    },
    {
      code: "KeyV",
      callback: () => {
        console.log("Visitante");
        setShortcut("Visitante -> KeyV");
      },
    },
  ]);

  useEffect(() => {
    const shortcutHandler = ShortcutHandler;

    shortcutHandler.configure(shortcuts);
    shortcutHandler.subscribe();

    return () => shortcutHandler.unsubscribe();
  }, [shortcuts]);

  return (
    <>
      <Head>
        <title>Shortcut Example</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main} style={inter.style}>
        <h2>{shortcut}</h2>

        <div>
          {shortcuts.map((shortcut) => {
            return <p key={shortcut.code}> AltKey + {shortcut.code}</p>;
          })}
        </div>
      </main>
    </>
  );
}
